from collections.abc import Generator
from datetime import datetime
import json
import sys
from pathlib import Path

from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool


BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

from app.agent import risk_analysis as risk_analysis_module  # noqa: E402
from app.db.base import Base  # noqa: E402
from app.db.session import get_db  # noqa: E402
from app.llm.factory import get_llm_provider  # noqa: E402
from app.llm.mock import MockLLMProvider  # noqa: E402
from app.main import app  # noqa: E402
from app.schemas.agent import (  # noqa: E402
    KnowledgeSearchToolResult,
    ToolKnowledgeResult,
)
from app.schemas.device import AlarmRecordCreate, DeviceCreate, RuntimeDataCreate  # noqa: E402
from app.services import device as device_service  # noqa: E402


def test_multi_device_risk_analysis_api_runs_full_tool_chain_and_saves_history(
    monkeypatch,
) -> None:
    client, SessionLocal = _build_client()
    db = SessionLocal()
    try:
        _seed_devices(db)
    finally:
        db.close()

    knowledge_queries: list[str] = []

    def fake_search(input_data):
        knowledge_queries.append(input_data.query)
        if "E101" in input_data.query:
            return _knowledge_result(
                alarm_code="E101",
                source="e101_maintenance_manual.md#chunk-0",
                filename="e101_maintenance_manual.md",
                content="E101 indicates temperature abnormality and requires cooling inspection.",
                distance=0.18,
            )
        if "E201" in input_data.query:
            return _knowledge_result(
                alarm_code="E201",
                source="e201_vibration_manual.md#chunk-0",
                filename="e201_vibration_manual.md",
                content="E201 indicates abnormal vibration and requires bearing inspection.",
                distance=0.16,
            )
        if "E203" in input_data.query:
            return _knowledge_result(
                alarm_code="E203",
                source="e203_controller_manual.md#chunk-0",
                filename="e203_controller_manual.md",
                content="E203 indicates abnormal motor operation and requires load inspection.",
                distance=0.2,
            )
        if "E404" in input_data.query:
            return _knowledge_result(
                alarm_code="E404",
                source="e404_sensor_manual.md#chunk-0",
                filename="e404_sensor_manual.md",
                content="E404 indicates communication abnormality and requires link inspection.",
                distance=0.25,
            )
        return KnowledgeSearchToolResult(ok=True, results=[])

    monkeypatch.setattr(risk_analysis_module, "run_search_knowledge_tool", fake_search)
    provider = MockLLMProvider(
        response={
            "summary": "Fleet risk report generated by LLM.",
            "overall_risk_level": "high",
            "key_findings": ["DEV-001, DEV-002, and DEV-003 have unresolved alarms."],
            "recommended_actions": ["Prioritize alarm devices and inspect related subsystems."],
            "warnings": [],
        }
    )
    app.dependency_overrides[get_llm_provider] = lambda: provider

    try:
        response = client.post(
            "/agent/risk-analysis",
            json={"query": "Analyze all current device risks and check DEV-999", "knowledge_top_k": 3},
        )
        history_response = client.get("/diagnosis/history")

        assert response.status_code == 200
        data = response.json()
        assert data["summary"] == "Fleet risk report generated by LLM."
        assert data["overall_risk_level"] == "high"
        assert "Data quality warning" in " ".join(data["warnings"])
        assert "DEV-999" in " ".join(data["warnings"])
        assert "DEV-999" not in [
            item["device"]["device_code"] for item in data["device_risks"]
        ]
        assert data["tools_used"] == [
            "list_devices",
            "get_device_status",
            "get_device_alarms",
            "search_knowledge",
            "llm_risk_report",
        ]
        assert data["sources"] == [
            "e203_controller_manual.md#chunk-0",
            "e404_sensor_manual.md#chunk-0",
            "e101_maintenance_manual.md#chunk-0",
            "e201_vibration_manual.md#chunk-0",
        ]

        device_risks = {
            item["device"]["device_code"]: item for item in data["device_risks"]
        }
        assert list(device_risks)[0] == "DEV-003"
        assert device_risks["DEV-001"]["knowledge_sources"] == [
            "e203_controller_manual.md#chunk-0",
            "e404_sensor_manual.md#chunk-0",
        ]
        assert device_risks["DEV-002"]["knowledge_sources"] == [
            "e404_sensor_manual.md#chunk-0"
        ]
        assert device_risks["DEV-003"]["knowledge_sources"] == [
            "e101_maintenance_manual.md#chunk-0"
        ]
        assert device_risks["DEV-005"]["knowledge_sources"] == [
            "e201_vibration_manual.md#chunk-0"
        ]
        assert device_risks["DEV-004"]["risk_level"] == "normal"

        assert any("E101" in query and "handling steps" in query for query in knowledge_queries)
        assert any("E201" in query and "handling steps" in query for query in knowledge_queries)
        assert any("E203" in query and "handling steps" in query for query in knowledge_queries)
        assert sum(1 for query in knowledge_queries if "E404" in query) == 2

        llm_user_payload = json.loads(provider.calls[0][1].content)
        assert "knowledge_evidence" in llm_user_payload
        assert [
            (item["device_code"], item["alarm_code"], item["results"][0]["source"])
            for item in llm_user_payload["knowledge_evidence"]
        ] == [
            ("DEV-001", "E203", "e203_controller_manual.md#chunk-0"),
            ("DEV-001", "E404", "e404_sensor_manual.md#chunk-0"),
            ("DEV-002", "E404", "e404_sensor_manual.md#chunk-0"),
            ("DEV-003", "E101", "e101_maintenance_manual.md#chunk-0"),
            ("DEV-005", "E201", "e201_vibration_manual.md#chunk-0"),
        ]

        assert history_response.status_code == 200
        history = history_response.json()
        assert len(history) == 1
        assert history[0]["problem_summary"] == "Fleet risk report generated by LLM."
        assert history[0]["sources"] == data["sources"]

        detail_response = client.get(f"/diagnosis/history/{history[0]['report_id']}")
        assert detail_response.status_code == 200
        detail = detail_response.json()
        assert detail["response"] is None
        assert detail["risk_report"]["summary"] == "Fleet risk report generated by LLM."
        assert detail["rag_sources"][0]["source"] == "e203_controller_manual.md#chunk-0"

        trace = detail["trace"]
        assert trace["mode"] == "multi_device_risk"
        assert trace["router_tools"] == [
            "list_devices",
            "get_device_status",
            "get_device_alarms",
            "search_knowledge",
        ]

        tool_results = trace["tool_results"]
        status_calls = [
            item for item in tool_results if item["tool_name"] == "get_device_status"
        ]
        alarm_calls = [
            item for item in tool_results if item["tool_name"] == "get_device_alarms"
        ]
        knowledge_calls = [
            item for item in tool_results if item["tool_name"] == "search_knowledge"
        ]
        assert [item["result"]["device_code"] for item in status_calls] == [
            "DEV-001",
            "DEV-002",
            "DEV-003",
            "DEV-004",
            "DEV-005",
        ]
        assert [item["result"]["device_code"] for item in alarm_calls] == [
            "DEV-001",
            "DEV-002",
            "DEV-003",
            "DEV-004",
            "DEV-005",
        ]
        assert [
            (item["result"]["device_code"], item["result"]["alarm_code"])
            for item in knowledge_calls
        ] == [
            ("DEV-001", "E203"),
            ("DEV-001", "E404"),
            ("DEV-002", "E404"),
            ("DEV-003", "E101"),
            ("DEV-005", "E201"),
        ]
        assert [
            (item["device_code"], item["alarm_code"], item["query"], item["source"])
            for item in trace["rag_results"]
        ] == [
            ("DEV-001", "E203", "E203 电机运行异常 handling steps", "e203_controller_manual.md#chunk-0"),
            ("DEV-001", "E404", "E404 通信异常 handling steps", "e404_sensor_manual.md#chunk-0"),
            ("DEV-002", "E404", "E404 通信异常 handling steps", "e404_sensor_manual.md#chunk-0"),
            ("DEV-003", "E101", "E101 温度异常 handling steps", "e101_maintenance_manual.md#chunk-0"),
            ("DEV-005", "E201", "E201 振动异常 handling steps", "e201_vibration_manual.md#chunk-0"),
        ]
    finally:
        app.dependency_overrides.clear()
        Base.metadata.drop_all(bind=SessionLocal.kw["bind"])


def test_multi_device_risk_analysis_llm_fallback_still_returns_tools(
    monkeypatch,
) -> None:
    client, SessionLocal = _build_client()
    db = SessionLocal()
    try:
        _seed_devices(db)
    finally:
        db.close()

    monkeypatch.setattr(
        risk_analysis_module,
        "run_search_knowledge_tool",
        lambda input_data: KnowledgeSearchToolResult(ok=True, results=[]),
    )
    app.dependency_overrides[get_llm_provider] = lambda: MockLLMProvider(
        error=RuntimeError("provider secret")
    )

    try:
        response = client.post("/agent/risk-analysis", json={"query": "Analyze all current device risks"})

        assert response.status_code == 200
        data = response.json()
        assert data["device_risks"]
        assert data["tools_used"][:3] == [
            "list_devices",
            "get_device_status",
            "get_device_alarms",
        ]
        assert "智能推理服务暂时不可用，已生成确定性风险汇总。" in data["warnings"]
        assert "provider secret" not in response.text
    finally:
        app.dependency_overrides.clear()
        Base.metadata.drop_all(bind=SessionLocal.kw["bind"])


def _build_client() -> tuple[TestClient, sessionmaker]:
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    SessionLocal = sessionmaker(
        bind=engine,
        autoflush=False,
        expire_on_commit=False,
    )
    Base.metadata.create_all(bind=engine)

    def override_get_db() -> Generator[Session, None, None]:
        db = SessionLocal()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    return TestClient(app), SessionLocal


def _seed_devices(db: Session) -> None:
    now = datetime.utcnow()
    dev_001 = device_service.create_device(
        db,
        DeviceCreate(
            device_code="DEV-001",
            name="Pump A",
            device_type="pump",
            location="Workshop A",
            is_online=True,
        ),
    )
    dev_002 = device_service.create_device(
        db,
        DeviceCreate(
            device_code="DEV-002",
            name="Motor B",
            device_type="motor",
            location="Workshop B",
            is_online=True,
        ),
    )
    dev_003 = device_service.create_device(
        db,
        DeviceCreate(
            device_code="DEV-003",
            name="Sensor C",
            device_type="sensor",
            location="Workshop C",
            is_online=True,
        ),
    )
    dev_004 = device_service.create_device(
        db,
        DeviceCreate(
            device_code="DEV-004",
            name="Compressor D",
            device_type="compressor",
            location="Workshop D",
            is_online=True,
        ),
    )
    dev_005 = device_service.create_device(
        db,
        DeviceCreate(
            device_code="DEV-005",
            name="Vibration Motor E",
            device_type="motor",
            location="Workshop E",
            is_online=True,
        ),
    )
    device_service.create_runtime_data(
        db,
        dev_001,
        RuntimeDataCreate(
            temperature=58.0,
            voltage=228.0,
            current=8.8,
            vibration=0.32,
            status="warning",
            recorded_at=now,
        ),
    )
    device_service.create_runtime_data(
        db,
        dev_002,
        RuntimeDataCreate(
            temperature=45.0,
            voltage=226.0,
            current=7.0,
            vibration=0.34,
            status="warning",
            recorded_at=now,
        ),
    )
    device_service.create_runtime_data(
        db,
        dev_003,
        RuntimeDataCreate(
            temperature=71.0,
            voltage=224.0,
            current=3.0,
            vibration=0.12,
            status="warning",
            recorded_at=now,
        ),
    )
    device_service.create_runtime_data(
        db,
        dev_004,
        RuntimeDataCreate(
            temperature=39.0,
            voltage=229.0,
            current=4.0,
            vibration=0.18,
            status="normal",
            recorded_at=now,
        ),
    )
    device_service.create_runtime_data(
        db,
        dev_005,
        RuntimeDataCreate(
            temperature=55.0,
            voltage=230.5,
            current=5.8,
            vibration=0.62,
            status="warning",
            recorded_at=now,
        ),
    )
    device_service.create_alarm_record(
        db,
        dev_001,
        AlarmRecordCreate(
            alarm_code="E203",
            alarm_level="medium",
            message="电机运行异常",
            is_resolved=False,
            occurred_at=now,
        ),
    )
    device_service.create_alarm_record(
        db,
        dev_001,
        AlarmRecordCreate(
            alarm_code="E404",
            alarm_level="low",
            message="通信异常",
            is_resolved=False,
            occurred_at=now,
        ),
    )
    device_service.create_alarm_record(
        db,
        dev_002,
        AlarmRecordCreate(
            alarm_code="E404",
            alarm_level="medium",
            message="通信异常",
            is_resolved=False,
            occurred_at=now,
        ),
    )
    device_service.create_alarm_record(
        db,
        dev_003,
        AlarmRecordCreate(
            alarm_code="E101",
            alarm_level="high",
            message="温度异常",
            is_resolved=False,
            occurred_at=now,
        ),
    )
    device_service.create_alarm_record(
        db,
        dev_005,
        AlarmRecordCreate(
            alarm_code="E201",
            alarm_level="medium",
            message="振动异常",
            is_resolved=False,
            occurred_at=now,
        ),
    )


def _knowledge_result(
    *,
    alarm_code: str,
    source: str,
    filename: str,
    content: str,
    distance: float,
) -> KnowledgeSearchToolResult:
    return KnowledgeSearchToolResult(
        ok=True,
        results=[
            ToolKnowledgeResult(
                chunk_id={"E101": 1, "E201": 4, "E203": 2, "E404": 3}[alarm_code],
                document_id={"E101": 1, "E201": 4, "E203": 2, "E404": 3}[alarm_code],
                filename=filename,
                chunk_index=0,
                content=content,
                source=source,
                distance=distance,
            )
        ],
    )
